# Generated by Django 4.1.2 on 2022-12-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('ci', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fecha', models.CharField(max_length=10)),
                ('cantidad_habitaciones', models.IntegerField()),
            ],
        ),
    ]
