# Generated by Django 4.1.5 on 2023-01-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
