# Generated by Django 4.1.5 on 2023-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0002_alter_disponibilidad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
